#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Plenty.Droid.Resource", IsApplication=true)]

namespace Plenty.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Worklight.Xamarin.Android.Resource.String.library_name = global::Plenty.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int asparagus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bakedpotato = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bbqribs = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int beerbottle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int belugalentils = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int catfood = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int cheesetasting = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int coffeebeans = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int coffeeroasting = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Events = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int fillyourgrowler = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int grillingsecrets = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int learntocook = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int mashedpotatoes = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int meetorganicgrower = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Menu = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int NUTS = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Offers = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int pasta = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Potatoes = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Recommendations = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int rotisschix = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int salmon = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int snacknuts = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int steak = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int tofu = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int UserMenu = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int vegcooking = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int wine = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int winetasting = 2130837534;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int library_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
